In [1]:
# Problem 4: Matrix Transpose and Inverse
# Problem 4 Part 2
import numpy as np

# generate 3 3x3 matrices 
M_1 = np.random.randint(-10, 11, size = (3,3))
M_2 = np.random.randint(-10, 11, size = (3,3))
M_3 = np.random.randint(-10, 11, size = (3,3))

print("Matrix 1: ", M_1)
print("Matrix 2: ", M_2)
print("Matrix 3: ", M_3)

Matrix 1:  [[-1  9 -6]
 [10 -9 -4]
 [-5 -3 -4]]
Matrix 2:  [[ 6  5 -7]
 [-9  4  2]
 [10 -5  6]]
Matrix 3:  [[-6  0  9]
 [ 1 -7  1]
 [ 8  9  5]]


In [2]:
# calculate inverses using packages
M_1_inv = np.linalg.inv(M_1)
M_2_inv = np.linalg.inv(M_2)
M_3_inv = np.linalg.inv(M_3)

# round to two decimals for readability 
print("Matrix 1 Inverse: ", np.round(M_1_inv, decimals = 2))
print("Matrix 2 Inverse: ", np.round(M_2_inv, decimals = 2))
print("Matrix 3 Inverse: ", np.round(M_3_inv, decimals = 2))

Matrix 1 Inverse:  [[ 0.02  0.06 -0.09]
 [ 0.06 -0.03 -0.07]
 [-0.08 -0.05 -0.08]]
Matrix 2 Inverse:  [[0.06 0.01 0.07]
 [0.14 0.2  0.09]
 [0.01 0.15 0.13]]
Matrix 3 Inverse:  [[-0.05  0.1   0.07]
 [ 0.   -0.12  0.02]
 [ 0.08  0.06  0.05]]


In [3]:
# compute product of matrix and inverse to check for identity matrix
prod_1 = M_1 @ M_1_inv
prod_2 = M_2 @ M_2_inv
prod_3 = M_3 @ M_3_inv

# round to two decimals for readability 
print("Matrix 1 and Inverse Product: ", np.round(prod_1, decimals = 2))
print("Matrix 2 and Inverse Product: ", np.round(prod_2, decimals = 2))
print("Matrix 3 and Inverse Product: ", np.round(prod_3, decimals = 2))

Matrix 1 and Inverse Product:  [[ 1. -0. -0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]
Matrix 2 and Inverse Product:  [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-0.  0.  1.]]
Matrix 3 and Inverse Product:  [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]
